version: '3.9'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ghmc_data:/var/lib/mysql

volumes:
  ghmc_data:
